version: 0.2

phases:
  install:
    commands:
      - echo "Downloading Hugo"
      - curl -L -o hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz"
      - tar -zxf hugo.tar.gz
      - mv hugo /usr/local/bin
  pre_build:
    commands:
      - git submodule update --init --recursive
  build:
    commands:
      - echo "Starting build"
      - hugo --baseURL $BASE_URL
  post_build:
    commands:
      - echo "Build complete"
      - echo "Syncing output to s3"
      - aws s3 sync --delete public s3://$S3_BUCKET
      - echo "Invalidating CloudFront distribution"
      - aws	cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /\* 
artifacts:
  files:
    - 'public/**/*'
