version: 0.2

phases:
  install:
    commands:
      - echo "Downloading Hugo"
      - curl -L -o hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.91.2/hugo_extended_0.91.2_Linux-64bit.tar.gz
      - tar -zxf hugo.tar.gz
      - mv hugo /usr/local/bin
  build:
    commands:
      - echo "Starting build"
      - hugo --baseURL https://nathanharkenrider.com
  post_build:
    commands:
      - echo "Build complete"
      - echo "Syncing output to s3"
      - aws s3 sync --delete public s3://nathanharkenrider.com
      - echo "Invalidating CloudFront distribution"
      - aws	cloudfront create-invalidation --distribution-id E253QIZ0H3S6J8 --paths /\* 
artifacts:
  files:
    - 'public/**/*'
