baseurl = "https://nathanharkenrider.com"
title = "Nathan Harkenrider"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "NateHark"

[params]
    author = "Nathan Harkenrider"
    info = "Dad, Developer, Frequent Fighter of Virtual Fires"
    description = "Nathan Harkenrider's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "img/profile.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/NateHark/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/NateHark/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/blog/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
