languageCode = "en-us"
title = "Nathan Harkenrider"
baseurl = "https://nathanharkenrider.com/"
theme = "aerial"

[params]
  name = "Nathan Harkenrider"
  about = "Engineering Leader @Smartsheet &nbsp;&bull;&nbsp; Dad"
  copyright = "Nathan Harkenrider"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/nathanharkenrider"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/NateHark"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://www.twitter.com/NateHark"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/nathan.harkenrider"
