languageCode = "en-us"

title = "Nathan Harkenrider"

theme = "hugo-theme-water"

[params]
  author = "Nathan Harkenrider"
  
  description = '''
  Hey All! My name is Nathan Harkenrider. I'm an engineering leader, runner, and dad, among other things. 
  I've served in many roles from individual contributor to executive leadership at 
  a variety of organizations ranging from early-stage startups to publicly traded companies. My writing 
  tends to focus on technology leadership, but I may post about other topics of interest occasionally.
  '''

[menu]
  [[menu.main]]
    name = "About"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-to-square"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Projects"
    pre = "mug-hot"
    url = "/projects/"
    weight = 4

  [[menu.social]]
    name = "LinkedIn"
    pre = "linkedin"
    url = "https://linkedin.com/in/nathanharkenrider"
    weight = 1

  [[menu.social]]
    name = "Github"
    pre = "github"
    url = "https://github.com/NateHark"
    weight = 2

  [[menu.social]]
    name = "Bluesky"
    pre = "bluesky"
    url = "https://bsky.app/profile/natehark.bsky.social"
    weight = 3